import Head from "next/head";

export const HeadMolecule = () => {
  return (
    <Head>
      <title>ポケモン（英語で）いえるかな？</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/pikachu.ico" />
    </Head>
  );
};
