import type { NextApiRequest, NextApiResponse } from 'next'

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  res.status(200).json([
    { "No": "001", "NameJa": "フシギダネ", "Origin": "bulb(球根) + dinosaur(恐竜) " },
    { "No": "002", "NameJa": "フシギソウ", "Origin": "ivy(ツタ) + dinosaur(恐竜) " },
    { "No": "003", "NameJa": "フシギバナ", "Origin": "venus flytrap(ハエジコク) + dinosaur(恐竜) " },
    { "No": "004", "NameJa": "ヒトカゲ", "Origin": "char(焦がす) + salamander(トカゲ) " },
    { "No": "005", "NameJa": "リザード", "Origin": "char(焦がす) + chameleon(カメレオン) " },
    { "No": "006", "NameJa": "リザードン", "Origin": "char(焦がす) + lizard(トカゲ) " },
    { "No": "007", "NameJa": "ゼニガメ", "Origin": "squirt(噴出させる+ 水鉄砲) + turtle(カメ, ウミガメ) " },
    { "No": "008", "NameJa": "カメール", "Origin": "war(戦争) + tortoise(カメ, リクガメ) + turtle(カメ, ウミガメ) " },
    { "No": "009", "NameJa": "カメックス", "Origin": "blast(爆破) + tortoise(カメ, リクガメ) " },
    { "No": "010", "NameJa": "キャタピー", "Origin": "caterpillar(イモムシ) " },
    { "No": "011", "NameJa": "トランセル", "Origin": "metamorphosis(変態) + pod(繭) " },
    { "No": "012", "NameJa": "バタフリー", "Origin": "butterfly(蝶) + free(自由) " },
    { "No": "013", "NameJa": "ビードル", "Origin": "worm(イモムシ) + needle(針) " },
    { "No": "014", "NameJa": "コクーン", "Origin": "cocoon(繭) " },
    { "No": "015", "NameJa": "スピアー", "Origin": "bee(蜂) + drill(ドリル) " },
    { "No": "016", "NameJa": "ポッポ", "Origin": "pigeon(鳩) + budgie(セキセイインコ) " },
    { "No": "017", "NameJa": "ピジョン", "Origin": "pigeon(鳩) + otto(イタリア語:8) " },
    { "No": "018", "NameJa": "ピジョット", "Origin": "pigeon(鳩) + jet(ジェット) " },
    { "No": "019", "NameJa": "コラッタ", "Origin": "rat(ドブネズミ) + attack(攻撃) " },
    { "No": "020", "NameJa": "ラッタ", "Origin": "rat(ドブネズミ) + eradicate(根絶する) " },
    { "No": "021", "NameJa": "オニスズメ", "Origin": "spear(槍) + sparrow(スズメ) " },
    { "No": "022", "NameJa": "オニドリル", "Origin": "fear(恐怖) + sparrow(スズメ) " },
    { "No": "023", "NameJa": "アーボ", "Origin": "snake(ヘビ) の逆さ読み" },
    { "No": "024", "NameJa": "アーボック", "Origin": "cobra(コブラ) の逆さ読み" },
    { "No": "025", "NameJa": "ピカチュウ", "Origin": "ぴかぴか(光を表す擬態語) + ちゅう(ネズミの鳴き声) " },
    { "No": "026", "NameJa": "ライチュウ", "Origin": "雷 + ちゅう(ネズミの鳴き声) " },
    { "No": "027", "NameJa": "サンド", "Origin": "sand(砂) + shrew(トガリネズミ) " },
    { "No": "028", "NameJa": "サンドパン", "Origin": "sand(砂) + slash(切りつける) " },
    { "No": "029", "NameJa": "ニドラン♀", "Origin": "needle(針) " },
    { "No": "030", "NameJa": "ニドリーナ", "Origin": "needle(針) + -a(イタリア語:女性名詞の語尾) " },
    { "No": "031", "NameJa": "ニドクイン", "Origin": "needle(針) + queen(女王) " },
    { "No": "032", "NameJa": "ニドラン♂", "Origin": "needle(針) " },
    { "No": "033", "NameJa": "ニドリーノ", "Origin": "needle(針) + -o(イタリア語:男性名詞の語尾) " },
    { "No": "034", "NameJa": "ニドキング", "Origin": "needle(針) + king(王) " },
    { "No": "035", "NameJa": "ピッピ", "Origin": "clef(フランス語:音符) + fairy(妖精) " },
    { "No": "036", "NameJa": "ピクシー", "Origin": "clef(フランス語:音符) + fable(寓話, 神話) " },
    { "No": "037", "NameJa": "ロコン", "Origin": "vulpes(ラテン語:キツネ) + six(6) " },
    { "No": "038", "NameJa": "キュウコン", "Origin": "nine tails(九尾) " },
    { "No": "039", "NameJa": "プリン", "Origin": "jiggly(揺れ動く) + puff(膨れ) " },
    { "No": "040", "NameJa": "プクリン", "Origin": "wiggly(揺れ動く) + stuff(詰め込む) " },
    { "No": "041", "NameJa": "ズバット", "Origin": "快傑ズバット+ bat(コウモリ) " },
    { "No": "042", "NameJa": "ゴルバット", "Origin": "ghoul(グルー(怪物の一種) ) + bat(コウモリ) " },
    { "No": "043", "NameJa": "ナゾノクサ", "Origin": "odd(奇妙な) + radish(ハツカダイコン) " },
    { "No": "044", "NameJa": "クサイハナ", "Origin": "gloom(憂鬱) + bloom(花) " },
    { "No": "045", "NameJa": "ラフレシア", "Origin": "vile(下劣な) + plume(羽) " },
    { "No": "046", "NameJa": "パラス", "Origin": "parasite(寄生虫) " },
    { "No": "047", "NameJa": "パラセクト", "Origin": "parasite(寄生虫) + insect(昆虫) " },
    { "No": "048", "NameJa": "コンパン", "Origin": "venom(毒) + gnat(羽虫) " },
    { "No": "049", "NameJa": "モルフォン", "Origin": "venom(毒) + moth(ガ) " },
    { "No": "050", "NameJa": "ディグダ", "Origin": "dig(掘る) + -let(接尾辞:小さい) " },
    { "No": "051", "NameJa": "ダグトリオ", "Origin": "dug(digの過去形) + trio(イタリア語:三人組) " },
    { "No": "052", "NameJa": "ニャース", "Origin": "meow(ネコの鳴き声) " },
    { "No": "053", "NameJa": "ペルシアン", "Origin": "Persian(ペルシャネコ) " },
    { "No": "054", "NameJa": "コダック", "Origin": "psychic(超能力) + duck(あひる) " },
    { "No": "055", "NameJa": "ゴルダック", "Origin": "なし(日本語名のゴルダック)" },
    { "No": "056", "NameJa": "マンキー", "Origin": "man(男) + monkey(サル) " },
    { "No": "057", "NameJa": "オコリザル", "Origin": "prime(導火線をつける, ガソリンを注ぐ) + ape(サル) + primate(霊長目) " },
    { "No": "058", "NameJa": "ガーディ", "Origin": "growl(動物が唸る) + lithe(しなやかな) " },
    { "No": "059", "NameJa": "ウインディ", "Origin": "arcane(秘密の) + ardent(燃えている) + canine(イヌ科) " },
    { "No": "060", "NameJa": "ニョロモ", "Origin": "polliwog(オタマジャクシ) + wag(揺れ動く) " },
    { "No": "061", "NameJa": "ニョロゾ", "Origin": "polliwog(オタマジャクシ) + whirl(渦巻き) " },
    { "No": "062", "NameJa": "ニョロボン", "Origin": "polliwog(オタマジャクシ) + wrath(激怒) " },
    { "No": "063", "NameJa": "ケーシィ", "Origin": "Abrakadabra(アブラ・カダブラ(呪文の一種) ) " },
    { "No": "064", "NameJa": "ユンゲラー", "Origin": "Abrakadabra(アブラ・カダブラ(呪文の一種) ) " },
    { "No": "065", "NameJa": "フーディン", "Origin": "英語圏で一般的な呪文・おまじないの言葉" },
    { "No": "066", "NameJa": "ワンリキー", "Origin": "macho(男らしい, マッチョな) + chop(チョップ) " },
    { "No": "067", "NameJa": "ゴーリキー", "Origin": "macho(男らしい, マッチョな) + choke(窒息させる) " },
    { "No": "068", "NameJa": "カイリキー", "Origin": "macho(男らしい, マッチョな) + champ(チャンピオン) " },
    { "No": "069", "NameJa": "マダツボミ", "Origin": "bell(鐘) + sprout(芽) " },
    { "No": "070", "NameJa": "ウツドン", "Origin": "weeping(しだれる) + bell(鐘) " },
    { "No": "071", "NameJa": "ウツボット", "Origin": "victory(勝利) + tree(木) + bell(鐘) " },
    { "No": "072", "NameJa": "メノクラゲ", "Origin": "tentacle(触手) + cool(クールな) " },
    { "No": "073", "NameJa": "ドククラゲ", "Origin": "tentacle(触手) + cruel(残酷な) " },
    { "No": "074", "NameJa": "イシツブテ", "Origin": "geo-(連結詞:土地の, 地球の) + dude(野郎) " },
    { "No": "075", "NameJa": "ゴローン", "Origin": "gravel(砂利) + er(接尾辞:～する人) " },
    { "No": "076", "NameJa": "ゴローニャ", "Origin": "golem(ゴーレム) " },
    { "No": "077", "NameJa": "ポニータ", "Origin": "pony(子馬) + bonita(スペイン語:可愛い) " },
    { "No": "078", "NameJa": "ギャロップ", "Origin": "rapid(急速な) + dash(ダッシュ) " },
    { "No": "079", "NameJa": "ヤドン", "Origin": "slow(遅い) + slowpoke(のろま) " },
    { "No": "080", "NameJa": "ヤドラン", "Origin": "slow(鈍い) + bro(兄弟) " },
    { "No": "081", "NameJa": "コイル", "Origin": "magnetite(磁鉄鉱) + mite(少量) " },
    { "No": "082", "NameJa": "レアコイル", "Origin": "magneton(磁子) + ton(トン, 多量の) " },
    { "No": "083", "NameJa": "カモネギ", "Origin": "farfetched(こじつけの, 不自然な)" },
    { "No": "084", "NameJa": "ドードー", "Origin": "dodo(ドードー(鳥)) + duo(二人組) " },
    { "No": "085", "NameJa": "ドードリオ", "Origin": "dodo(ドードー(鳥)) + trio(三人組) " },
    { "No": "086", "NameJa": "パウワウ", "Origin": "seal(アシカ, アザラシ) " },
    { "No": "087", "NameJa": "ジュゴン", "Origin": "dew(露, しずく) + dugong(ジュゴン) " },
    { "No": "088", "NameJa": "ベトベター", "Origin": "grime((皮膚などにこびりついた) よごれ, あか) + er(接尾辞:～する人) " },
    { "No": "089", "NameJa": "ベトベトン", "Origin": "muck(汚物, たい肥) " },
    { "No": "090", "NameJa": "シェルダー", "Origin": "shell(貝殻) + shelter(シェルター, 避難所) " },
    { "No": "091", "NameJa": "パルシェン", "Origin": "clam(二枚貝) + oyster(蠣) " },
    { "No": "092", "NameJa": "ゴース", "Origin": "gas(ガス) + ghastly(ぞっとする) " },
    { "No": "093", "NameJa": "ゴースト", "Origin": "haunt(幽霊が出没する) + er(接尾辞:～する人) " },
    { "No": "094", "NameJa": "ゲンガー", "Origin": "doppelgänger(ドイツ語:ドッペルゲンガー) " },
    { "No": "095", "NameJa": "イワーク", "Origin": "onyx(シマメノウ) " },
    { "No": "096", "NameJa": "スリープ", "Origin": "drowsy(眠い) + zzz(オノマトペ:グーグー) " },
    { "No": "097", "NameJa": "スリーパー", "Origin": "hypnosis(催眠術) " },
    { "No": "098", "NameJa": "クラブ", "Origin": "crab(蟹) + crabby(不機嫌な) " },
    { "No": "099", "NameJa": "キングラー", "Origin": "king(王様) + fiddler crab(シオマネキ) " },
    { "No": "100", "NameJa": "ビリリダマ", "Origin": "volt(ボルト) ,orb(球) " },
    { "No": "101", "NameJa": "マルマイン", "Origin": "electric(電気の) + explode(爆発する) + electrode(電極) " },
    { "No": "102", "NameJa": "タマタマ", "Origin": "execute(実行する, 遂行する) + egg(卵) " },
    { "No": "103", "NameJa": "ナッシー", "Origin": "execute(実行する, 遂行する) + egg(卵) + tor(接尾語:〜する人) " },
    { "No": "104", "NameJa": "カラカラ", "Origin": "cub((肉食動物の) こども) + bone(骨) " },
    { "No": "105", "NameJa": "ガラガラ", "Origin": "marrow(骨髄) + whack(強打) " },
    { "No": "106", "NameJa": "サワムラー", "Origin": "hit(打撃) + monster(モンスター) + Bruce Lee(ブルース・リー) " },
    { "No": "107", "NameJa": "エビワラー", "Origin": "hit(打撃) + monster(モンスター) + Jackie Chan(ジャッキー・チェン) " },
    { "No": "108", "NameJa": "ベロリンガ", "Origin": "lick(なめる) + tongue(舌) " },
    { "No": "109", "NameJa": "ドガース", "Origin": "coughing(咳) " },
    { "No": "110", "NameJa": "マタドガス", "Origin": "wheezing(喘息) " },
    { "No": "111", "NameJa": "サイホーン", "Origin": "rhino(サイ) + horn(ツノ) " },
    { "No": "112", "NameJa": "サイドン", "Origin": "rhino(サイ) + don(恐竜の名前の接尾語) " },
    { "No": "113", "NameJa": "ラッキー", "Origin": "chance(好機, 偶然, 運命) " },
    { "No": "114", "NameJa": "モンジャラ", "Origin": "tangle(絡まる) + Medusa(メドゥーサ) " },
    { "No": "115", "NameJa": "ガルーラ", "Origin": "kangaroo(カンガルー) + Khan(ハーン:遊牧民の君主などが名乗る称号) " },
    { "No": "116", "NameJa": "タッツー", "Origin": "seahorse(タツノオトシゴ) + horsie(お馬さん) " },
    { "No": "117", "NameJa": "シードラ", "Origin": "sea(海) + dragon(ドラゴン) " },
    { "No": "118", "NameJa": "トサキント", "Origin": "goldfish(金魚) + queen(女王) " },
    { "No": "119", "NameJa": "アズマオウ", "Origin": "sea(海) + king(王様) " },
    { "No": "120", "NameJa": "ヒトデマン", "Origin": "starfish(ヒトデ) + you(あなた:スターミーのmeとの対比) " },
    { "No": "121", "NameJa": "スターミー", "Origin": "starfish(ヒトデ) + me(私) " },
    { "No": "122", "NameJa": "バリヤード", "Origin": "Mr.(男性の敬称) + mime(パントマイム) " },
    { "No": "123", "NameJa": "ストライク", "Origin": "scythe(鎌) + er(接尾辞:～する人) " },
    { "No": "124", "NameJa": "ルージュラ", "Origin": "jinx(不運, ジンクス) " },
    { "No": "125", "NameJa": "エレブー", "Origin": "electric(電気の) + buzz(機械などがブンブン言う) " },
    { "No": "126", "NameJa": "ブーバー", "Origin": "magma(マグマ) + fulmar(フルマカモメ) " },
    { "No": "127", "NameJa": "カイロス", "Origin": "pincer((エビ, カニの) はさみ) " },
    { "No": "128", "NameJa": "ケンタロス", "Origin": "Taurus(ラテン語:雄牛) " },
    { "No": "129", "NameJa": "コイキング", "Origin": "magic(魔法の) + carp(コイ) " },
    { "No": "130", "NameJa": "ギャラドス", "Origin": "なし(日本語名のギャラドス) " },
    { "No": "131", "NameJa": "ラプラス", "Origin": "la place(フランス語:席, 座席) " },
    { "No": "132", "NameJa": "メタモン", "Origin": "ditto(コピーする, 同じことを繰り返す) " },
    { "No": "133", "NameJa": "イーブイ", "Origin": "evolution(進化) " },
    { "No": "134", "NameJa": "シャワーズ", "Origin": "vapor(蒸気) + eon(永劫) " },
    { "No": "135", "NameJa": "サンダース", "Origin": "jolt(ショックを与える) + eon(永劫) " },
    { "No": "136", "NameJa": "ブースター", "Origin": "flare(炎が燃えあがる) + eon(永劫) " },
    { "No": "137", "NameJa": "ポリゴン", "Origin": "polygon(多角形) " },
    { "No": "138", "NameJa": "オムナイト", "Origin": "オウムガイ(日本語) + Ammonite(アンモナイト) " },
    { "No": "139", "NameJa": "オムスター", "Origin": "オウムガイ(日本語) + star(星) " },
    { "No": "140", "NameJa": "カブト", "Origin": "兜, カブトガニ(日本語) " },
    { "No": "141", "NameJa": "カブトプス", "Origin": "兜, カブトガニ(日本語) + triops(カブトエビ) " },
    { "No": "142", "NameJa": "プテラ", "Origin": "aero-(接頭辞:空気の, 航空の) + pterodactyl(プテロダクティルス) " },
    { "No": "143", "NameJa": "カビゴン", "Origin": "snore(いびき) + relax(リラックス) " },
    { "No": "144", "NameJa": "フリーザー", "Origin": "arctic(北極の) + uno(スペイン語:1) " },
    { "No": "145", "NameJa": "サンダー", "Origin": "zap(電撃) + dos(スペイン語:2) " },
    { "No": "146", "NameJa": "ファイヤー", "Origin": "molten(熱で溶けた) + tres(スペイン語:3) " },
    { "No": "147", "NameJa": "ミニリュウ", "Origin": "dragon(ドラゴン) + tiny(とても小さい) " },
    { "No": "148", "NameJa": "ハクリュー", "Origin": "dragon(ドラゴン) + air(空気+ 空中) " },
    { "No": "149", "NameJa": "カイリュー", "Origin": "dragon(ドラゴン) + knight(騎士) " },
    { "No": "150", "NameJa": "ミュウツー", "Origin": "mutant(突然変異) + new(新しい) + two(2) " },
    { "No": "151", "NameJa": "ミュウ", "Origin": "mutant(突然変異) + new(新しい) " },
  ])
}
