import Head from 'next/head';
import { Footer } from './Footer';
import { Header } from './Header';


export default function Layout({ children }) {
  return (
    <div className="h-screen bg-violet-400">
      <Head>
        <title>ポケモン（英語で）いえるかな？</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pikachu.ico" />
      </Head>

      <div className='sticky top-0 z-50'>
        <Header />
      </div>

      <div className="relative bg-pink-200">
        {children}
      </div>

      <div className="sticky bottom-0 z-50 w-screen">
        <Footer />
      </div>

    </div>
  )
}
