import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const [totalAccess, setTotalAccess] = useState(0)

  return (
    <div className={styles.container}>
      <Head>
        <title>ポケモン（英語で）言えるかな？</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pikachu.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ポケモン（英語で）言えるかな？
        </h1>

        <img src={`/pokedex/025.png`} alt="pikachu" />

        <p className={styles.description}>
          あなたは{totalAccess}人めのポケモントレーナーです。
        </p>

        <div className="flex flex-col h-32 gap-4 hover:cursor-pointer">
          <Link href="/pokemon-list"><p>ポケモン図鑑</p></Link>
          <Link href="pokemon-battle"><p>言えるかな？</p></Link>
          <Link href="ranking"><p>ランキング</p></Link>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
